name: macOS

on: [push]

jobs:
    build-macos:
        strategy:
            matrix:
                include:
                    - qt_version: 5.15
                    - qt_version: 6.7

        runs-on: macos-latest
        name: build-macos-qt${{matrix.qt_version}}

        steps:
        - name: Set environment variables
          run: |
              echo QT_VERSION_MAJOR=$(echo ${{matrix.qt_version}} | cut -d. -f1) >> $GITHUB_ENV

        - name: Checkout
          uses: actions/checkout@v2

        - name: Install Qt
          run: brew install qt@$QT_VERSION_MAJOR

        - name: Install OpenCascade
          run: brew install opencascade

        - name: Install Assimp
          run: brew install assimp

        - name: Get count of CPU cores
          uses: SimenB/github-actions-cpu-cores@v1
          id: cpu-cores

        - name: Build
          run: |
              echo QT_VERSION_MAJOR=$QT_VERSION_MAJOR
              mkdir ${{github.workspace}}/build
              cd ${{github.workspace}}/build
              cmake --version
              cmake .. \
                    -DMayo_BuildTests=ON \
                    -DMayo_BuildPluginAssimp=ON \
                    -DQT_DIR=$(brew --prefix qt@$QT_VERSION_MAJOR)/lib/cmake/Qt$QT_VERSION_MAJOR
              cmake --build . \
                    --config Release \
                    --parallel ${{steps.cpu-cores.outputs.count}}

        - name: Execute Unit Tests
          working-directory: ${{github.workspace}}/build
          run: |
              ./mayo.app/Contents/MacOS/mayo --runtests

        - name: Create dmg file
          working-directory: ${{github.workspace}}/build
          run: |
              $(brew --prefix qt@$QT_VERSION_MAJOR)/bin/macdeployqt mayo.app -dmg
              mv mayo.dmg Mayo-0.9.0-macOS-arm64.dmg

        - name: Upload dmg file
          uses: actions/upload-artifact@v4
          with:
              name: Mayo-0.9.0-macOS-arm64-dmg
              path: |
                  ${{github.workspace}}/build/Mayo-0.9.0-macOS-arm64.dmg
                  #${{github.workspace}}/build/MayoConv-0.9.0-macOS-arm64.dmg

